### ISSUE TITLE
License used?

### ISSUE THREAD

**Issue by dltj** [ruven/iipmooviewer#54]
I am adding an entry for IIPMooViewer in the FOSS4Lib registry (https://foss4lib.org/), and I don't see an open source license listed.  Could you add that to the code repository, please?

**Comment by ruven** [comment]
Thanks for adding this to FOSS4Lib. It's GPL3, as is the IIPImage server.

**Comment by dltj** [comment]
Great!  Thank you... https://foss4lib.org/package/iipmooviewer
