### ISSUE TITLE
error in deepzoom protocol

### ISSUE THREAD

**Issue by sbarex** [ruven/iipmooviewer#60]
There is a error in the implementation of `getThumbnailURL` inside deepzoom.js protocol.
The `thumbLevel` var is defined from the value of `this.tileSize` that is never setted.
I suggest to change the `parseMetaData` function to set this variable adding this line before the return statement:
```JS
this.tileSize = {w: ts, h: ts};
```
And, inside `getThumbnailURL` change the definition of `thumbLevel` with this:
```JS
var thumbLevel = Math.log(this.tileSize.w) / Math.LN2 - 1;
```

**Comment by ruven** [comment]
OK thanks, I've just uploaded an update based on your suggestion. I simplified slightly as we don't need to keep separate width and height tile sizes for Deepzoom.
