### ISSUE TITLE
zooming does not work

### ISSUE THREAD

**Issue by umehlig** [ruven/iipmooviewer#65]
I just started to experiment with iipmooviewer, using the example index.html. Loading and panning the image works well, however, the zoom buttons and the +/- keys do not work. Also, specifying a zoom level as URL parameter doesn't appear to work. I'm using Firefox 48.0 on Ubuntu 16.04 with standard iipserver on Apache2. Any help is much appreciated!

**Comment by ruven** [comment]
Try using the developer tools in Firefox. Does the console give any error messages when you click +/- ?

**Comment by umehlig** [comment]
No, it doesn't ... However, I just discovered that I apparently did not prepare the TIFF image properly. I just had used ImageMagick's -define tiff:tile-geometry=256x256 without prefixing the output file name by   ptif:somefile.tif to get I pyramidal TIFF. With a new image created with the respective output specification, zooming works, at least up to 100%. This is in the documentation of iipserver -- sorry! Thank you for your help!

**Comment by ruven** [comment]
OK, glad it's now working!
