### ISSUE TITLE
iiif mode: wrong tilesize for last image

### ISSUE THREAD

**Issue by renevoorburg** [ruven/iipmooviewer#71]
![issue71](https://cloud.githubusercontent.com/assets/465625/23269989/9c60b5dc-f9f2-11e6-8abe-7aaac8b67cf0.png)

This issue occurs only in iiif-mode. Let say we have an image that is  in the lowest resolution is, let say 800 pixels wide and 70 pixels heigh. This hight is less than the default tile height of 256 pixels (70 pixels). However, also the fourth image is requested to have size !256x256. This will result in a scaled image, higher than 70 pixels.

Image width should be 800 - 3x256 = 32, height should be 70.  With iiif (!256,256) this 32x70 image wil be resized, which clearly is not desired.

**Comment by renevoorburg** [comment]
perhaps this is the same issue as mentioned in #40

**Comment by ruven** [comment]
This should be fixed by https://github.com/ruven/iipmooviewer/commit/152213faf4bae10fea0ce24fc9849ac77248ba26
