### ISSUE TITLE
Add support for PNG as output format

### ISSUE THREAD

**Issue by beaudet** [ruven/iipmooviewer#72]
We require PNG in order to better integrate the IIP Image server with our Web CMS (Adobe Experience Manager).  The UI components that AEM's DAM uses makes an assumption that the format of output is PNG.  In addition, according to:

http://iipimage.sourceforge.net/2014/12/iiif/

IIP is nearly Level 2 IIIF Image API compliant and just requires PNG output to reach it so this change would make IIP Image server fully IIIF Image API version 2.0 compliant.  Of course, the IIIF Image API is up to version 2.1 now and I'm unsure about IIP's chances of also being IIIF Image API version 2.1 compliant after this change, but perhaps it will be...?

**Comment by beaudet** [comment]
I see there are references to PNGCompressor.h in configure.ac suggesting that work on that had begun or at least the scaffolding for it had begun.  Is there an actual PNGCompressor.cc or PNGCompressor.h that I should start with rather than starting from scratch?

**Comment by ruven** [comment]
Yes, I did a preliminary version of this, but never quite finished. It probably just needs some tweaking to get it working:

https://gist.github.com/ruven/10d9e3595928ed848ea6cc9d63789e11
https://gist.github.com/ruven/63541387d4c7d8dea1b106c694df144a

**Comment by beaudet** [comment]
Great, I'll start from there.  Thanks.

**Comment by beaudet** [comment]
I created this issue in the wrong repository so closing it.  Should have been in iipsrv repo.
