### ISSUE TITLE
Print from gallery

### ISSUE THREAD

**Issue by aperi2007** [ruven/iipmooviewer#76]
Hi,
When in gallery is not possible to print using the navbutton dedicated.
I try this code

    var gallery = new Gallery( "targetframe", {
	images: image_list,
        navigation: {
          buttons: ['zoomIn','zoomOut','rotateLeft','rotateRight','reset','print']
        }
    });

But without success

Is possible to print from gallery ?

**Comment by ruven** [comment]
OK, I just added a fix to allow you to do that. Please check out the latest version: https://github.com/ruven/iipmooviewer/commit/4171314a4ffda2525677f55b8aca17e496355182

**Comment by aperi2007** [comment]
I try it and have this error.

TypeError: this.options is undefined[Ulteriori informazioni] iipmooviewer-2.0-compressed.js:159:99 

My code is this:

<pre>
    var gallery = new Gallery( "targetframe", {
	images: image_list
    });


</pre>

I test better...

**Comment by ruven** [comment]
You must be using an old version. The compressed version of the iipmooviewer js is iipmooviewer-2.0-min.js not iipmooviewer-2.0-compressed.js. Make sure you use the latest code from github.

**Comment by aperi2007** [comment]
The iipmooviewer-2.0-compressed.js was created using this sintax:

java -jar compiler.jar --js src/mootools-more-1.6.0.js --js src/iipmooviewer-2.0.js --js src/navigation.js --js src/scale.js --js src/touch.js --js src/protocols/iip.js --js src/protocols/iiif.js --js src/protocols/zoomify.js --js src/protocols/djatoka.js --js src/protocols/deepzoom.js --js src/annotations.js --js src/annotations-edit.js --js src/blending.js --js src/lang/help.it.js --js src/gallery.js --js_output_file javascript/iipmooviewer-2.0-compressed.js --compilation_level SIMPLE_OPTIMIZATIONS

So I guess it was with the latest code

**Comment by ruven** [comment]
OK, try again, I just updated gallery.js again. It should work now.

**Comment by aperi2007** [comment]
ok.
It work.
Thx Ruven.

**Comment by ruven** [comment]
OK good!
