### ISSUE TITLE
iipmooviewer vs remote IIIF-server: how to solve 'Request header field x-requested-with is not allowed'

### ISSUE THREAD

**Issue by abubelinha** [ruven/iipmooviewer#81]
As #80 is taking longer to solve than I expected, I am exploring other remote image storage possibilities so I can keep using iipmooviewer as my preferred client.

One of them is the [Internet Archive](https://www.archive.org):
- https://blog.archive.org/2015/10/23/zoom-in-to-9-3-million-internet-archive-books-and-images-through-iiif/
- https://blog.archive.org/2023/09/18/making-iiif-official-at-the-internet-archive/

So I tried to implement an example to explore [this image](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/full/512,/0/default.jpg) using the following code:

```html
<!DOCTYPE html>
<html lang="en">

 <head>
  <meta charset="utf-8" />
  <meta name="DC.creator" content="Ruven Pillay &lt;ruven@users.sourceforge.netm&gt;"/>
  <meta name="DC.title" content="IIPMooViewer 2.0: HTML5 High Resolution Image Viewer"/>
  <meta name="DC.subject" content="IIPMooViewer; IIPImage; Visualization; HTML5; Ajax; High Resolution; Internet Imaging Protocol; IIP"/>
  <meta name="DC.description" content="IIPMooViewer is an advanced javascript HTML5 image viewer for streaming high resolution scientific images"/>
  <meta name="DC.rights" content="Copyright &copy; 2003-2012 Ruven Pillay"/>
  <meta name="DC.source" content="http://iipimage.sourceforge.net"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
  <meta http-equiv="X-UA-Compatible" content="IE=9" />

  <link rel="stylesheet" type="text/css" media="all" href="css/iip.min.css" />

  <!-- Basic example style for a 100% view -->
  <style type="text/css">
    body{
      height: 100%;
      padding: 0;
      margin: 0;
    }
    div#viewer{
      height: 100%;
      min-height: 100%;
      width: 100%;
      position: absolute;
      top: 0;
      left: 0;
      margin: 0;
      padding: 0;
    }	
  </style>

  <link rel="shortcut icon" href="images/iip-favicon.png" />
  <link rel="apple-touch-icon" href="images/iip.png" />

  <title>IIPMooViewer 2.0 :: HTML5 High Resolution Image Viewer</title>

  <script src="https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js"></script>
  <script type="text/javascript" src="js/iipmooviewer-2.0-min.js"></script>
  <script type="text/javascript" src="./src/protocols/iiif.js"></script>
  <script type="text/javascript">
	var server = 'https://iiif.archive.org/image/iiif/3';
	var image = 'platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2';
	var credit = '<a href="https://archive.org/details/platowithenglish04platuoft">Internet Archive: <i>Plato, with an English translation</i> by H.N. Fowler, W.R.M. Lamb & R.G. Bury (1914)</a>';

    new IIPMooViewer( "viewer", {
	server: server,
	image: image,
	protocol: "IIIF",
	credit: credit,
	// scale: 23.9 // you set it according to each image scale if you wish to take measures
    });
  </script>
 </head>
 <body>
   <div id="viewer"></div>
 </body>

```
I get this javascript error:
> `Access to XMLHttpRequest at 'https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/info.json' from origin 'http://localhost:81' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.`

So I guess iipmooviewer is failing at [this point](https://github.com/ruven/iipmooviewer/blob/b8481c73abebe8de9e092821dc288c508923b5f1/src/mootools-core-1.6.0.js#L5725) in mootools-core-1.6.0.js:
```javascript
	headers: {
		'X-Requested-With': 'XMLHttpRequest',
		'Accept': 'text/javascript, text/html, application/xml, text/xml, */*'
	},
``` 
Any ideas about how to solve this?
Perhaps related to [mootools-core/issues#2381](https://github.com/mootools/mootools-core/issues/2381)? 

I can browse the same remote image with similar tests of other javascript clients like [Leaflet-IIIF plugin](https://github.com/mejackreed/Leaflet-IIIF) or [OpenSeadragon](https://github.com/openseadragon/openseadragon), so it doesn't seem to be a problem with the remote IIIF server CORS configuration (unless iipmooviewer is requesting things that other clients don't need).

Thanks in advance
@abubelinha

**Comment by abubelinha** [comment]
I figured out how to avoid this error but I don't know if the trick may cause some other problems in iipmooviewer.
I used [a javascript solution](https://github.com/mootools/mootools-core/issues/2381#issuecomment-25206493) by  @djafferian, and tried it successfully in two different positions:
- At the beginning of my `script` tag (just before defining `server` and `image`) in my main .html file
- At the end of `/src/protocols/iiif.js` (a cleaner solution so it is only included when working with IIIF servers).

Perhaps this can be further tuned so the code below is only used whenever `protocol: "IIIF"` has been set in main .html file (but I don't know how to do it).
```javascript
	/* 
	Taken from @djafferian https://github.com/mootools/mootools-core/issues/2381#issuecomment-25206493
	Workaround to prevent "Request header field x-requested-with is not allowed" error
	Described in https://github.com/ruven/iipmooviewer/issues/81
	*/
	Class.refactor(Request, {
		initialize: function (options) {
			this.previous(options);
			if (!('headers' in options && 'X-Requested-With' in options.headers)) {
				delete this.headers['X-Requested-With']; 
			}
		}
	});
```

If I understood correctly, mootools sets that Request header by default ([it seems to be needed for it to work](https://github.com/mootools/mootools-core/issues/2381#issuecomment-25206493)).
So it's up to you to delete it in order to let iipmooviewer work with some IIIF servers which don't set their headers the same way.
When I did it, I didn't find any other javascript issues so far (but for now I only used basic viewer functionality: no rotations, annotations, etc).

Some more comments I found about this:
- https://stackoverflow.com/questions/29344284/x-requested-with-is-not-allowed-by-access-control-allow-headers/29344528#29344528
- https://stackoverflow.com/questions/9830546/mootools-request-class-and-cors/22233103#22233103
- https://stackoverflow.com/questions/18445337/mootools-cors-request-vs-native-javascript/18607750#18607750

@ruven: I keep the issue open so you can take a look at it and decide about this.
I believe it is a good example you could add to documentation showing how to use iipmooviewer client combined with an open remote IIIF server.

If you try it, you will probably also find some wrong tile requests which I think are minor bugs in iiif.js (but I think that should be a different issue).

Thanks once again for this nice software!
@abubelinha

**Comment by ruven** [comment]
Thanks for looking into this. CORS requests when using iipsrv as an IIIF back-end handle this header correctly, but it is indeed an issue for certain other IIIF servers. I just committed a fix (https://github.com/ruven/iipmooviewer/commit/5c71ded5b8d0a94ff011ac900b33573deaf5e4a8) that only deletes the header when using IIIF

`if( this.protocol.__proto__ === Protocols.IIIF.prototype ) delete metadata.headers["X-Requested-With"];`

**Comment by abubelinha** [comment]
Great @ruven !

I hope you can provide a fully working example against a remote IIIF server (even if it is not Zenodo for now).
Hopefully a public and open one (any one you know which is fully IIIF compliant).

In the above example image the paper texture is not good to show them, but I think iipmooviewer is still making some computing errors in right & bottom border tiles (please try it yourself).

Thanks a lot in advance

**Comment by ruven** [comment]
> I hope you can provide a fully working example against a remote IIIF server (even if it is not Zenodo for now).

Here's a demo running with your image from the Internet Archive: https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/internet-archive.html

It seems to work properly, even for the bottom edge tiles
