### ISSUE TITLE
updates in iiif.js for compatibility with some IIIF servers

### ISSUE THREAD

**Issue by abubelinha** [ruven/iipmooviewer#82]
Looking into [src/protocols/iiif.js](https://github.com/ruven/iipmooviewer/blob/a8edf930424f2fd68e60610c0cd956802a5df140/src/protocols/iiif.js) (lines 26, 67 & 73) I think some IIIF servers use the naming `default.jpg` instead of `native.jpg`

Internet Archive example image ([info.json](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/info.json)):
- [default.jpg](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/full/300,/0/default.jpg) works
- [native.jpg](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/full/300,/0/native.jpg) fails

Thanks
@abubelinha

**EDIT:** 
When solving #81 I also found bad tile responses from (at least) iiif.archive.org server when iipmooviewe zoom level goes (apparently beyond?) maximum. 
The server returned "**404 invalid size**" for some requested urls like [this](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/0,1024,512,512/full/0/default.jpg) or [this](https://iiif.archive.org/image/iiif/3/platowithenglish04platuoft%2Fplatowithenglish04platuoft_jp2.zip%2Fplatowithenglish04platuoft_jp2%2Fplatowithenglish04platuoft_0002.jp2/512,1536,512,512/full/0/default.jpg?1704451170027).

I "solved" it modifying [`iiif.js` line 24](https://github.com/ruven/iipmooviewer/blob/a8edf930424f2fd68e60610c0cd956802a5df140/src/protocols/iiif.js#L24) (`src += "/full";`) like this, but probably there is a better solution:
```javascript
src += "/" + this.tileSize.w + ","; 
```

I link a copy of my [`iiif.js`](https://gist.github.com/abubelinha/96c89f8e7537411c04166847a5574269) file with all suggested changes.

**Comment by ruven** [comment]
I've just made a commit (https://github.com/ruven/iipmooviewer/commit/a6dfa8f082ee2eea4eb5f1fb9af958bfc4584cc5) that incorporates your suggestions. Thanks! It also fixes the problems with the images in the final row.

I tried with your Internet Archive example and it all seems to now work properly. Please test it and let me know if you run into any other issues.

**Comment by abubelinha** [comment]
I can confirm it works now. Thanks a lot @ruven !!

I didn't detect any usage issues, but I guess [iiif.js#L90](https://github.com/ruven/iipmooviewer/blob/a6dfa8f082ee2eea4eb5f1fb9af958bfc4584cc5/src/protocols/iiif.js#L90) still contains an obsolete reference to old IIIF version '_native.jpg_' which I didn't realize in my previous message.  
(I tell you just in case it causes any other issues later on).
