### ISSUE TITLE
help with adding annotations (button is empty and failing)

### ISSUE THREAD

**Issue by abubelinha** [ruven/iipmooviewer#84]
Sorry if I am missing something already documented but I am having troubles for setting up basic annotation system.

I load `mootools-core-1.6.0.js, mootools-more-1.6.0.js, iipmooviewer-2.0.js, iiif.js, blending.js, navigation.js, scale.js, touch.js, annotations.js, annotations-edit.js, help.en.js` in that order, before my own script (which is basically the same described in #81 plus latest @ruven's corrections).
I added a single annotation array to the IIPMooViewer object, and it works properly (I can double click the current annotation, edit / move / delete it): 
```javascript
var annotations = { 1:{...} } 
...
new IIPMooViewer( "viewer", {
	...
	annotations: annotations,
	navigation: {
		draggable: true,
		buttons: ['reset','zoomIn','zoomOut', 'rotateLeft', 'rotateRight', 'addAnnotation']
	}
});

```
But that's all I could do.

These are my troubles for **adding** annotations:
- I see a new 'addAnnotation' button but it has no icon inside. I think [its file is missing in this repository](https://github.com/ruven/iipmooviewer/tree/master/images), isn't it?
  That's fine if we are supposed to add custom icons for non default buttons, but I suggest this to be documented.
- When I click that empty button, nothing happens (and no javascript error is fired). Should I do anything else in my code? (I don't think this is related to the missing icon, because when I delete files for the other icons in the bar, their buttons are empty too but they keep working).
- I couldn't find an official iipmooviewer 2.0 working example with enabled addAnnotation functionality, in order to compare my code. Is there any?
- In #56 I found a link to this @jcupitt demo http://jcupitt.github.io/iipmooviewer/ (thanks!).
  It works but it doesn't seem to use the same approach documented in current iipmooviewer's version (it's 9 years old). 
  It initializes `var annotations = [ {} ]` instead of `var annotations = {1: {}}`.
  I tried to do that too but no way ... I don't understand why its `addAnnotation` button works and mine doesn't.
  Looking to the comments, it seems @jcupitt [added the missing icon](https://github.com/ruven/iipmooviewer/issues/56#issuecomment-86519255) and @ruven [merged those changes](https://github.com/ruven/iipmooviewer/issues/56#issuecomment-86901291), but for some reason they are gone again.

Thanks in advance for any help you can provide!
@abubelinha

**Comment by ruven** [comment]
In fact there's no default button for adding annotations, as the idea was that most developers would want to embed the viewer into their own system. To do this there is a javascript function newAnnotation(), which you can be called to create a new empty annotation if you include the file src/annotations-edit.js. Double-clicking existing annotations allows you to edit also.

In the example you found, the source code has been modified to add this new button, which is why it doesn't work for you.

Maybe it would in fact be good to include such a button, as it's the only button you really need to be separate (edit and delete are attached to each annotation). If you have any suggestions for a nice icon for this, let me know!

**Comment by abubelinha** [comment]
> there is a javascript function newAnnotation(), which you can be called to create a new empty annotation if you include the file src/annotations-edit.js

Thanks @ruven, I read all documentation and was aware of that.  
But I expected that function to be already called when I click the button (once I already added it to the navigation toolbar). 
Why is it more complicated than when adding other optional buttons? 
i.e. rotation buttons -once included in navigation bar- already call their corresponding functions when they are clicked.

Sorry by my javascript ignorance but how can I make that _button click - function launch_ happen?  
Looking to @jcupitt demo I see a difference in [iipmooviewer-2.0.js](https://github.com/jcupitt/iipmooviewer/blob/gh-pages/src/iipmooviewer-2.0.js#L1241-L1245):   should I do the same?

I would prefer a way to activate addAnotation functionality without touching the main iipmooviewer-2.0.js file (i.e. adding some javascript code directly in my .html file script). So I don't need to rewrite code when you update the script.

> If you have any suggestions for a nice icon for this, let me know!

Sure.  Either a pencil icon or a capital "A" like in @jcupitt example


BTW. Using @jcupitt demo above I realized I cannot add annotations when using mobile phone.
When I touch inside the annotation text boxes, nothing happens (I would expect the mobile keyboard to be displayed so I can edit title, category and text).

**Comment by ruven** [comment]
OK, I've just made a commit that adds this button and activates the functionality: https://github.com/ruven/iipmooviewer/commit/424f07794ee6b663f621ffca77da264ef3b642ff

You need to add "newAnnotation" to the list of buttons, not "addAnnotation". I ended up using this icon: https://iconduck.com/icons/85125/annotation, but maybe your choices are better. Anyway, we can change this later.

Here's an example demo: https://merovingio.c2rmf.cnrs.fr/iipimage/iipmooviewer/annotations.html

Once you have your annotations working, you need to save them somewhere, so you'll need to integrate some javascript to save these on a server somewhere. This is left deliberately open as this kind of data will usually be stored in a database
away from iipmooviewer or the IIPImage server.

**Comment by abubelinha** [comment]
Thank you very much @ruven, that works !!

I have a couple of questions:
- Does your example use some kind of advanced html which makes it incompatible with old browsers?
   Couldn't open it with my old ipad browsers (blank screen). But they used to open other iipmooviewer-2.0 tests I made in the past.
- Have annotations been tested in mobile? 
  I couldn't finish an annotation from any mobile phone (just tried 3 Android from my family).
  I can draw the annotation frame and fill in the three input boxes using "next" key to navigate, but then "next" dissapears and I cannot reach the Ok/Cancel/Delete buttons.
  When I try to press one of them with my finger, iipmooviewer behaves like if I was touching the underlying zoomable image.   

> you'll need to integrate some javascript to save these on a server somewhere

Thanks. I am already working on that. 
But I am basically interested in students adding annotations to our images as a class assignment. 
And they will mostly use mobile phones for browsing them, so ... I am stuck on this one for now.
